name: karasearch
description: "karasearch"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.3.0
  shared_preferences: ^2.5.2
  cupertino_icons: ^1.0.8

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/karaoke_icon.png"
  adaptive_icon_background: "#ffffff"
  #adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true